:test:(Events) Add reverting test for setBaseURI
ethernautdao/ethernauts pull request #139
Opened 2021-12-17 15:43 UTC by eloiGarrido

Add reverting test for `setBaseURI` function when `permanentUrl` is set to `true`

Closes #127

2021-12-17 15:44 UTC, mariobyn approved these changes

2021-12-18 20:11 UTC, mjlescano requested changes
CI is not passing

2021-12-19 18:53 UTC, eloiGarrido commented
I've reduced the value of `Random.test.js`'s `maxTokens` and `batchSize` by a factor of 10 which improves test speed tenfold.
Added  an assert for `getRandomNumberCount()` within minting tests to increase coverage to 100%

2021-12-20 12:07 UTC, mjlescano approved these changes

2021-12-20 12:07 UTC, merged